# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: 'k8s-pool'
  demands:
  - maven

#stages:
 # - stage: 
  #  jobs:
   # - job: 
    #  steps:
     # - task: Docker@2
      #  inputs:
       #   containerRegistry: 'webgoat-dcr'
        #  repository: 'gameof-life-webapp'
         # command: 'buildAndPush'
          #Dockerfile: '**/Dockerfile'
          #ddPipelineData: false
          #dBaseImageData: false

stages:
  - stage: 
    jobs:
    - job: 
      steps:
    
      - task: Maven@4
        inputs:
          mavenPomFile: 'pom.xml'
          publishJUnitResults: true
          testResultsFiles: '**/surefire-reports/TEST-*.xml'
          javaHomeOption: 'JDKVersion'
          mavenVersionOption: 'Default'
          mavenAuthenticateFeed: false
          effectivePomSkip: false
          sonarQubeRunAnalysis: false
    