# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: 'webgaot-pool'

stages:
  - stage: 
    jobs:
    - job: 
      steps:
      - task: Docker@2
        inputs:
          containerRegistry: 'webgoat-dcr'
          repository: 'gameof-life-webapp'
          command: 'buildAndPush'
          Dockerfile: '**/Dockerfile'
          addPipelineData: false
          addBaseImageData: false